signals:
  sig1:
    display_name: signal_1
    units: F
    min_value: 0
    max_value: 100
    max_rate_of_change: 10
    no_change_probability: 0.3
    plot_color: red
  sig2:
    display_name: signal_2
    units: F
    min_value: 0
    max_value: 200
    max_rate_of_change: 10
    no_change_probability: 0.3
    plot_color: purple
  sig3:
    display_name: signal_3
    units: F
    min_value: 0
    max_value: 300
    max_rate_of_change: 100
    no_change_probability: 0.3
    plot_color: blue
      

derived_signals:
  sig4:
    display_name: signal_4
    units: F
    equation: abs(sig1 - sig2)
    plot_color: brown
  sig5:
    display_name: signal_5
    units: F
    equation: max(sig1, sig2)
    plot_color: brown


ramp_config:
  ramp_start_time:
    min_value: 1
    max_value: 100
  ramp_duration:
    min_value : 0
    max_value: 50
  hold_duration:
    min_value : 0
    max_value : 100
  end_time: 
    value: 200

