signals:
  sig1:
    display_name: signal_1
    units: F
    parameters:
      magnitude: 
        distribution_type: uniform
        min_value: 0
        max_value: 100
      rate_of_change: 
        distribution_type: uniform
        min_value: -10
        max_value: 10
        set_to_0_probability: 0.3
    plot_color: red

  sig2:
    display_name: signal_2
    units: F
    parameters:
      magnitude: 
        distribution_type: uniform
        min_value: 0
        max_value: 200
      rate_of_change: 
        distribution_type: uniform
        min_value: -10
        max_value: 10
        set_to_0_probability: 0.3
    plot_color: purple
    
  sig3:
    display_name: signal_3
    units: F
    parameters:
      magnitude: 
        distribution_type: uniform
        min_value: 0
        max_value: 300
      rate_of_change: 
        distribution_type: uniform
        min_value: -100
        max_value: 100
        set_to_0_probability: 0.3
    plot_color: blue
      

derived_signals:
  sig4:
    display_name: signal_4
    units: F
    equation: abs(sig1 - sig2)
    plot_color: brown
  sig5:
    display_name: signal_5
    units: F
    equation: max(sig1, sig2)
    plot_color: brown


signal_generation:
  ramp:
    description: ramp jobs that contain symmetrical trapezoidal waveforms
    parameters:
      ramp_start_time: 
        distribution_type: uniform
        min_value: 1
        max_value: 10
      ramp_duration:
        distribution_type: uniform
        min_value: 0
        max_value: 50
      hold_duration:
        distribution_type: uniform
        min_value: 0
        max_value: 50
      end_time: 
        distribution_type: uniform
        min_value: 200
        max_value: 200

